name: crouter
description: A sample command-line application.
version: 0.0.8
homepage: https://github.com/chengbook/crouter

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  #执行shell命令
  process_run: ^0.11.0+2
  analyzer: any
  meta: any

#生成应用程序，在命令行中输入crouter运行命令行应用
executables:
  crouter: crouter

#配合executables时会把应用程序安装到本地
#pub global activate --source path ./
#运行
#pub global run crouter
#激活插件
#pub global activate crouter